[pytest]

addopts =
    --html=reports/report.html
    --self-contained-html
    -s
    -vv

filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning

markers =
    login: Verify login scenarios
    home: Verify elements in the home page
    scroll: Verify Scroll in the Infinite Scroll Page
    interactions: Verify interactions page
    TC: dynamic test case marker (e.g., @pytest.mark.TC1, @pytest.mark.TC2)
